<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductPlatformSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productPlatforms = [
            // Plataformas de Conexión y Superficie
            [
                'name' => 'Narrow',
                'slug' => 'narrow',
                'description' => 'Plataforma de conexión estrecha para implantes',
                'seo_description' => 'Plataforma Narrow: conexión estrecha para implantes dentales',
                'is_active' => true,
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Standard',
                'slug' => 'standard',
                'description' => 'Plataforma de conexión estándar para implantes',
                'seo_description' => 'Plataforma Standard: conexión estándar para implantes dentales',
                'is_active' => true,
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'I-ON',
                'slug' => 'i-on',
                'description' => 'Plataforma con tratamiento de superficie I-ON',
                'seo_description' => 'Plataforma I-ON: tratamiento de superficie para implantes',
                'is_active' => true,
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Multiunit',
                'slug' => 'multiunit',
                'description' => 'Plataforma de conexión multiunit para prótesis',
                'seo_description' => 'Plataforma Multiunit: conexión para rehabilitaciones protésicas',
                'is_active' => true,
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Superficie
            [
                'name' => 'SOL (Narrow)',
                'slug' => 'sol-narrow',
                'description' => 'Plataforma de superficie SOL en conexión narrow',
                'seo_description' => 'Plataforma SOL Narrow: superficie tratada para conexión estrecha',
                'is_active' => true,
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MOR (Superficie SLA)',
                'slug' => 'mor-superficie-sla',
                'description' => 'Plataforma de superficie MOR con tratamiento SLA',
                'seo_description' => 'Plataforma MOR SLA: superficie tratada con tecnología SLA',
                'is_active' => true,
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RBM (Superficie hidroxiapatita)',
                'slug' => 'rbm-superficie-hidroxiapatita',
                'description' => 'Plataforma de superficie RBM con hidroxiapatita',
                'seo_description' => 'Plataforma RBM: superficie con hidroxiapatita para osteointegración',
                'is_active' => true,
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'EVA (Sin montador)',
                'slug' => 'eva-sin-montador',
                'description' => 'Plataforma EVA sin montador para implantes',
                'seo_description' => 'Plataforma EVA: implantes sin montador para cirugía',
                'is_active' => true,
                'order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas Especiales
            [
                'name' => 'Cigomático',
                'slug' => 'cigomatico',
                'description' => 'Plataforma cigomática para rehabilitación',
                'seo_description' => 'Plataforma Cigomática: soluciones para rehabilitación cigomática',
                'is_active' => true,
                'order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Diámetro
            [
                'name' => 'Diámetro 1.5',
                'slug' => 'diametro-1.5',
                'description' => 'Plataforma de implantes de 1.5mm de diámetro',
                'seo_description' => 'Implantes de 1.5mm: plataforma para espacios reducidos',
                'is_active' => true,
                'order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diámetro 2.0',
                'slug' => 'diametro-2.0',
                'description' => 'Plataforma de implantes de 2.0mm de diámetro',
                'seo_description' => 'Implantes de 2.0mm: plataforma estándar para implantes',
                'is_active' => true,
                'order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hex in',
                'slug' => 'hex-in',
                'description' => 'Plataforma de conexión hexagonal interna',
                'seo_description' => 'Plataforma Hex in: conexión hexagonal interna para implantes',
                'is_active' => true,
                'order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Ortoimplantes
            [
                'name' => 'EVA',
                'slug' => 'eva',
                'description' => 'Plataforma EVA para ortoimplantes',
                'seo_description' => 'Plataforma EVA: sistema para ortoimplantes y mini-implantes',
                'is_active' => true,
                'order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ortoimplantes (Morelli)',
                'slug' => 'ortoimplantes-morelli',
                'description' => 'Plataforma de ortoimplantes Morelli',
                'seo_description' => 'Ortoimplantes Morelli: sistema de mini-implantes ortodónticos',
                'is_active' => true,
                'order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MOR/RBM/EVA',
                'slug' => 'mor-rbm-eva',
                'description' => 'Plataforma combinada MOR/RBM/EVA',
                'seo_description' => 'Plataforma MOR/RBM/EVA: combinación de tratamientos superficiales',
                'is_active' => true,
                'order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Kits Quirúrgicos
            [
                'name' => 'TKS SD (Kit compacto con ratchet)',
                'slug' => 'tks-sd-kit-compacto-ratchet',
                'description' => 'Plataforma TKS SD con kit compacto y ratchet',
                'seo_description' => 'TKS SD: kit compacto con sistema ratchet para cirugía',
                'is_active' => true,
                'order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TKS T8C SD (Kit compacto con torquímetro)',
                'slug' => 'tks-t8c-sd-kit-compacto-torquimetro',
                'description' => 'Plataforma TKS T8C SD con kit compacto y torquímetro',
                'seo_description' => 'TKS T8C SD: kit compacto con torquímetro para precisión',
                'is_active' => true,
                'order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TKM SD (Kit mediano con ratchet)',
                'slug' => 'tkm-sd-kit-mediano-ratchet',
                'description' => 'Plataforma TKM SD con kit mediano y ratchet',
                'seo_description' => 'TKM SD: kit mediano con sistema ratchet para cirugía',
                'is_active' => true,
                'order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TKM T8C SD (Kit mediano con torquímetro)',
                'slug' => 'tkm-t8c-sd-kit-mediano-torquimetro',
                'description' => 'Plataforma TKM T8C SD con kit mediano y torquímetro',
                'seo_description' => 'TKM T8C SD: kit mediano con torquímetro para precisión',
                'is_active' => true,
                'order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TKS CP (Kit compacto con ratchet)',
                'slug' => 'tks-cp-kit-compacto-ratchet',
                'description' => 'Plataforma TKS CP con kit compacto y ratchet',
                'seo_description' => 'TKS CP: kit compacto con sistema ratchet para cirugía',
                'is_active' => true,
                'order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TKS CP T8C (Kit compacto con torquímetro)',
                'slug' => 'tks-cp-t8c-kit-compacto-torquimetro',
                'description' => 'Plataforma TKS CP T8C con kit compacto y torquímetro',
                'seo_description' => 'TKS CP T8C: kit compacto con torquímetro para precisión',
                'is_active' => true,
                'order' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TKM CP (Kit mediano con ratchet)',
                'slug' => 'tkm-cp-kit-mediano-ratchet',
                'description' => 'Plataforma TKM CP con kit mediano y ratchet',
                'seo_description' => 'TKM CP: kit mediano con sistema ratchet para cirugía',
                'is_active' => true,
                'order' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TKM CP T8C (Kit mediano con torquímetro)',
                'slug' => 'tkm-cp-t8c-kit-mediano-torquimetro',
                'description' => 'Plataforma TKM CP T8C con kit mediano y torquímetro',
                'seo_description' => 'TKM CP T8C: kit mediano con torquímetro para precisión',
                'is_active' => true,
                'order' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Biomateriales
            [
                'name' => '0.5cc / 1cc / 2cc',
                'slug' => 'volumenes-0.5-1-2-cc',
                'description' => 'Plataforma de volúmenes 0.5cc, 1cc y 2cc',
                'seo_description' => 'Biomateriales en volúmenes 0.5cc, 1cc, 2cc para aplicación precisa',
                'is_active' => true,
                'order' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '1.5x2 cm / 2x3 cm',
                'slug' => 'dimensiones-1.5x2-2x3-cm',
                'description' => 'Plataforma de dimensiones 1.5x2cm y 2x3cm',
                'seo_description' => 'Biomateriales en tamaños 1.5x2cm y 2x3cm para regeneración',
                'is_active' => true,
                'order' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '10x10x1mm / 20x10x1mm',
                'slug' => 'dimensiones-10x10x1-20x10x1-mm',
                'description' => 'Plataforma de dimensiones 10x10x1mm y 20x10x1mm',
                'seo_description' => 'Láminas corticales en 10x10x1mm y 20x10x1mm',
                'is_active' => true,
                'order' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '10x10x10mm / 20x10x10mm',
                'slug' => 'dimensiones-10x10x10-20x10x10-mm',
                'description' => 'Plataforma de dimensiones 10x10x10mm y 20x10x10mm',
                'seo_description' => 'Bloques óseos en 10x10x10mm y 20x10x10mm',
                'is_active' => true,
                'order' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '15x15mm / 25x25mm / 30x40mm',
                'slug' => 'dimensiones-15x15-25x25-30x40-mm',
                'description' => 'Plataforma de dimensiones 15x15mm, 25x25mm y 30x40mm',
                'seo_description' => 'Membranas en múltiples tamaños para regeneración tisular',
                'is_active' => true,
                'order' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Color
            [
                'name' => 'Silver',
                'slug' => 'silver',
                'description' => 'Plataforma de color plata para biomateriales',
                'seo_description' => 'Biomateriales color plata: identificación visual para productos',
                'is_active' => true,
                'order' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blue',
                'slug' => 'blue',
                'description' => 'Plataforma de color azul para biomateriales',
                'seo_description' => 'Biomateriales color azul: identificación visual para productos',
                'is_active' => true,
                'order' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas Especiales de Biomateriales
            [
                'name' => 'Grafting plug',
                'slug' => 'grafting-plug',
                'description' => 'Plataforma de injertos tipo plug',
                'seo_description' => 'Grafting plug: sistema de injertos en formato plug',
                'is_active' => true,
                'order' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bovine grafting plug',
                'slug' => 'bovine-grafting-plug',
                'description' => 'Plataforma de injertos bovinos tipo plug',
                'seo_description' => 'Bovine grafting plug: injertos bovinos en formato plug',
                'is_active' => true,
                'order' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Osteosíntesis
            [
                'name' => 'Titanium mesh',
                'slug' => 'titanium-mesh',
                'description' => 'Plataforma de mallas de titanio',
                'seo_description' => 'Mallas de titanio: sistema para fijación y reconstrucción',
                'is_active' => true,
                'order' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Membrana PTFE Reonforced Titanium',
                'slug' => 'membrana-ptfe-reinforced-titanium',
                'description' => 'Plataforma de membranas PTFE reforzadas con titanio',
                'seo_description' => 'Membranas PTFE titanio: barreras reforzadas para regeneración',
                'is_active' => true,
                'order' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GBR Tetting Screw',
                'slug' => 'gbr-tetting-screw',
                'description' => 'Plataforma de tornillos de fijación GBR',
                'seo_description' => 'GBR Tetting Screw: tornillos para fijación en regeneración',
                'is_active' => true,
                'order' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GBR Bone Screw',
                'slug' => 'gbr-bone-screw',
                'description' => 'Plataforma de tornillos óseos GBR',
                'seo_description' => 'GBR Bone Screw: tornillos óseos para regeneración guiada',
                'is_active' => true,
                'order' => 36,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Tornillos
            [
                'name' => '3.5mm / 5mm',
                'slug' => 'tornillos-3.5-5-mm',
                'description' => 'Plataforma de tornillos de 3.5mm y 5mm',
                'seo_description' => 'Tornillos de 3.5mm y 5mm: sistema para osteosíntesis',
                'is_active' => true,
                'order' => 37,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Drivers
            [
                'name' => 'Piloto 1.2mm / Piloto 1.4mm / Piloto 1.8mm',
                'slug' => 'pilotos-1.2-1.4-1.8-mm',
                'description' => 'Plataforma de brocas piloto de 1.2mm, 1.4mm y 1.8mm',
                'seo_description' => 'Brocas piloto: sistema para preparación de sitios quirúrgicos',
                'is_active' => true,
                'order' => 38,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Driver manual GBR / Driver motor GBR / Driver Tachuela',
                'slug' => 'drivers-gbr-manual-motor-tachuela',
                'description' => 'Plataforma de drivers GBR manuales, motor y tachuela',
                'seo_description' => 'Drivers GBR: sistema completo para regeneración ósea guiada',
                'is_active' => true,
                'order' => 39,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Blister
            [
                'name' => 'Blister 3.5 / Blister 5.0',
                'slug' => 'blister-3.5-5.0',
                'description' => 'Plataforma de blister de 3.5 y 5.0',
                'seo_description' => 'Blister 3.5 y 5.0: empaque estéril para productos',
                'is_active' => true,
                'order' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Piezas de Mano
            [
                'name' => 'Pieza recta',
                'slug' => 'pieza-recta',
                'description' => 'Plataforma de piezas de mano rectas',
                'seo_description' => 'Pieza recta: instrumental dental para procedimientos directos',
                'is_active' => true,
                'order' => 41,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Contra Ángulo 20:1',
                'slug' => 'contra-angulo-20-1',
                'description' => 'Plataforma de contra ángulo 20:1',
                'seo_description' => 'Contra ángulo 20:1: sistema de reducción para precisión',
                'is_active' => true,
                'order' => 42,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Turbinas
            [
                'name' => 'Turbinas 45°',
                'slug' => 'turbinas-45-grados',
                'description' => 'Plataforma de turbinas a 45 grados',
                'seo_description' => 'Turbinas 45°: instrumental para acceso angular',
                'is_active' => true,
                'order' => 43,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sierra Reciprocante',
                'slug' => 'sierra-reciprocante',
                'description' => 'Plataforma de sierras reciprocantes',
                'seo_description' => 'Sierra reciprocante: sistema para cortes precisos',
                'is_active' => true,
                'order' => 44,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sierra Oscilante',
                'slug' => 'sierra-oscilante',
                'description' => 'Plataforma de sierras oscilantes',
                'seo_description' => 'Sierra oscilante: sistema para cortes delicados',
                'is_active' => true,
                'order' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plataformas de Motores
            [
                'name' => 'Motor de implantes',
                'slug' => 'motor-implantes',
                'description' => 'Plataforma de motores para implantes',
                'seo_description' => 'Motor de implantes: sistema para cirugía de implantología',
                'is_active' => true,
                'order' => 46,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Micro-motores',
                'slug' => 'micro-motores',
                'description' => 'Plataforma de micro-motores',
                'seo_description' => 'Micro-motores: sistema de alta precisión para odontología',
                'is_active' => true,
                'order' => 47,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('product_platforms')->insert($productPlatforms);
    }
}
