<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SystemProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $systemProducts = [
            // Sistemas de Implantes
            [
                'name' => 'Hex in (i5)',
                'slug' => 'hex-in-i5',
                'description' => 'Sistema de conexión Hexagonal interna para implantes',
                'seo_description' => 'Sistema Hex in i5: conexión hexagonal interna para implantes dentales',
                'is_active' => true,
                'order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cónico (I-ON)',
                'slug' => 'conico-ion',
                'description' => 'Sistema de conexión cónica con tratamiento de superficie I-ON',
                'seo_description' => 'Sistema Cónico I-ON: conexión cónica con tratamiento de superficie para implantes',
                'is_active' => true,
                'order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sub-Periósticos',
                'slug' => 'sub-periosticos',
                'description' => 'Sistema de implantes sub-periósticos para rehabilitación',
                'seo_description' => 'Implantes sub-periósticos: sistema para rehabilitación con implantes debajo del periostio',
                'is_active' => true,
                'order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Drivers',
                'slug' => 'drivers',
                'description' => 'Sistema de drivers y herramientas de inserción',
                'seo_description' => 'Drivers para implantes: sistema de herramientas para inserción protésica',
                'is_active' => true,
                'order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ortoimplantes',
                'slug' => 'ortoimplantes',
                'description' => 'Sistema de implantes ortodónticos y mini-implantes',
                'seo_description' => 'Ortoimplantes: sistema de mini-implantes para ortodoncia y anclaje',
                'is_active' => true,
                'order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sistemas de Kits Quirúrgicos
            [
                'name' => 'Kit Morelli',
                'slug' => 'kit-morelli',
                'description' => 'Sistema de kits quirúrgicos Morelli',
                'seo_description' => 'Kit Morelli: sistema de instrumental quirúrgico para implantología',
                'is_active' => true,
                'order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kit GBR',
                'slug' => 'kit-gbr',
                'description' => 'Sistema de kits para regeneración ósea guiada',
                'seo_description' => 'Kit GBR: sistema completo para regeneración ósea guiada',
                'is_active' => true,
                'order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sistemas de Biomateriales
            [
                'name' => 'Hueso (N - grano medio)',
                'slug' => 'hueso-n-grano-medio',
                'description' => 'Sistema de injertos óseos de grano medio',
                'seo_description' => 'Injertos óseos N grano medio: biomaterial para regeneración ósea',
                'is_active' => true,
                'order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hueso (G - grano grueso)',
                'slug' => 'hueso-g-grano-grueso',
                'description' => 'Sistema de injertos óseos de grano grueso',
                'seo_description' => 'Injertos óseos G grano grueso: biomaterial para reconstrucción ósea',
                'is_active' => true,
                'order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Membrana',
                'slug' => 'membrana',
                'description' => 'Sistema de membranas para regeneración tisular',
                'seo_description' => 'Membranas para regeneración: sistema de barreras tisulares guiadas',
                'is_active' => true,
                'order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lámina Cortical',
                'slug' => 'lamina-cortical',
                'description' => 'Sistema de láminas corticales para reconstrucción',
                'seo_description' => 'Láminas corticales: sistema para reconstrucción y regeneración ósea',
                'is_active' => true,
                'order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bloque',
                'slug' => 'bloque',
                'description' => 'Sistema de bloques óseos para reconstrucción',
                'seo_description' => 'Bloques óseos: sistema para reconstrucción maxilofacial',
                'is_active' => true,
                'order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hueso (Bovino)',
                'slug' => 'hueso-bovino',
                'description' => 'Sistema de injertos óseos de origen bovino',
                'seo_description' => 'Injertos óseos bovinos: biomateriales de origen bovino para regeneración',
                'is_active' => true,
                'order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BioMembrana (Bovino)',
                'slug' => 'bio-membrana-bovino',
                'description' => 'Sistema de biomembranas de origen bovino',
                'seo_description' => 'BioMembranas bovinas: membranas de origen bovino para regeneración',
                'is_active' => true,
                'order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hemosponge',
                'slug' => 'hemosponge',
                'description' => 'Sistema de esponjas hemostáticas',
                'seo_description' => 'Hemosponge: sistema de esponjas hemostáticas para cirugía',
                'is_active' => true,
                'order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sponge',
                'slug' => 'sponge',
                'description' => 'Sistema de esponjas para regeneración tisular',
                'seo_description' => 'Esponjas regenerativas: sistema para regeneración tisular guiada',
                'is_active' => true,
                'order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Antivirus Gel',
                'slug' => 'antivirus-gel',
                'description' => 'Sistema de geles antimicrobianos',
                'seo_description' => 'Antivirus Gel: sistema de geles antimicrobianos para cuidado post-quirúrgico',
                'is_active' => true,
                'order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bovine Graft Bioplant',
                'slug' => 'bovine-graft-bioplant',
                'description' => 'Sistema de injertos bovinos Bioplant',
                'seo_description' => 'Bovine Graft Bioplant: sistema de injertos bovinos para regeneración',
                'is_active' => true,
                'order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PerioFocus',
                'slug' => 'periofocus',
                'description' => 'Sistema de productos para periodoncia',
                'seo_description' => 'PerioFocus: sistema de productos especializados para periodoncia',
                'is_active' => true,
                'order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sistemas de Osteosíntesis
            [
                'name' => 'Mallas',
                'slug' => 'mallas',
                'description' => 'Sistema de mallas para osteosíntesis',
                'seo_description' => 'Mallas de osteosíntesis: sistema para fijación y reconstrucción',
                'is_active' => true,
                'order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tornillos',
                'slug' => 'tornillos-osteosintesis',
                'description' => 'Sistema de tornillos para osteosíntesis',
                'seo_description' => 'Tornillos de osteosíntesis: sistema para fijación maxilofacial',
                'is_active' => true,
                'order' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tachuelas (Bone Tac)',
                'slug' => 'tachuelas-bone-tac',
                'description' => 'Sistema de tachuelas óseas para fijación',
                'seo_description' => 'Tachuelas Bone Tac: sistema de fijación ósea mínimamente invasiva',
                'is_active' => true,
                'order' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sistemas de Instrumental
            [
                'name' => 'Disco de corte diamantado',
                'slug' => 'disco-corte-diamantado',
                'description' => 'Sistema de discos de corte diamantados',
                'seo_description' => 'Discos de corte diamantados: sistema para osteotomía precisa',
                'is_active' => true,
                'order' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Drills',
                'slug' => 'drills',
                'description' => 'Sistema de brocas y fresas quirúrgicas',
                'seo_description' => 'Drills quirúrgicos: sistema de brocas para cirugía dental',
                'is_active' => true,
                'order' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Piezas de mano',
                'slug' => 'piezas-mano',
                'description' => 'Sistema de piezas de mano quirúrgicas',
                'seo_description' => 'Piezas de mano quirúrgicas: sistema para instrumental dental',
                'is_active' => true,
                'order' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Motores',
                'slug' => 'motores',
                'description' => 'Sistema de motores para instrumental dental',
                'seo_description' => 'Motores dentales: sistema de motores para piezas de mano',
                'is_active' => true,
                'order' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('system_products')->insert($systemProducts);
    }
}
